In [1]:
import numpy as np

In [121]:
class NeuralNetwork(object):
    def __init__(self):
        self.inputLayerSize = 3
        self.hiddenLayerSize = 3
        self.outputLayerSize = 1
        
        self.w1 = np.random.randn(self.inputLayerSize, self.hiddenLayerSize)
        self.w2 = np.random.randn(self.hiddenLayerSize, self.outputLayerSize)
        print self.w1
        print self.w2
        
    def forward(self, x):
        self.net1 = np.dot(x, self.w1)
        self.z2   = self.sigmoid(self.net1)
        self.net2 = np.dot(self.z2, self.w2)
        output    = self.sigmoid(self.net2)
        return output
    
    def sigmoid(self, x):
        return (1./(1+np.exp(-x)))
    
    def sigmoidDifferentiation(self, x):
        return (self.sigmoid(x)*(1. - self.sigmoid(x)))
    
    def gradientDescend(self, x, target, stepSize, threshold):
        
        self.output = self.forward(x)
        error = self.calcError(target, self.output)
        
        itr = 0
        while(error > threshold):
            # Calculate delta Error
            delta2 = np.multiply(-(target - self.output), self.sigmoidDifferentiation(self.net2))
            dEdW2 = np.dot(self.z2.T, delta2)

            delta1 = np.dot(delta2, self.w2.T)*self.sigmoidDifferentiation(self.net1)
            dEdW1 = np.dot(x.T, delta1)

            # Update Weights
            self.w1 -= stepSize*dEdW1
            self.w2 -= stepSize*dEdW2

            self.output = self.forward(x)
            error = self.calcError(target, self.output)
            
            # Checking whether log likelihood is increasing
            if itr <= 15 or (itr <= 100 and itr % 10 == 0) or (itr <= 1000 and itr % 100 == 0) \
            or (itr <= 10000 and itr % 1000 == 0) or itr % 10000 == 0:
                print 'iteration %d: error = %f' %(itr, error)
            itr += 1
            
            
    def calcError(self, target, output):
        return 0.5 * sum((target - output)**2)

In [5]:
inputs = np.array([[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]])

In [6]:
print inputs

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


In [47]:
target = np.array([[0],[1],[1],[0],[1],[0],[0],[1]])
print target

[[0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]]


In [127]:
NN = NeuralNetwork()

[[ 0.64569584  0.44616639  0.49975748]
 [ 1.63482618  1.80544271 -0.37420078]
 [-1.68873458  1.53547202  1.35908382]]
[[ 0.37061108]
 [ 1.74058174]
 [-0.99530244]]


In [ ]:
NN.gradientDescend(inputs, target, 0.2, 0.0001)

iteration 0: error = 0.001000
iteration 1: error = 0.001000
iteration 2: error = 0.001000
iteration 3: error = 0.001000
iteration 4: error = 0.001000
iteration 5: error = 0.001000
iteration 6: error = 0.001000
iteration 7: error = 0.001000
iteration 8: error = 0.001000
iteration 9: error = 0.001000
iteration 10: error = 0.001000
iteration 11: error = 0.001000
iteration 12: error = 0.001000
iteration 13: error = 0.001000
iteration 14: error = 0.001000
iteration 15: error = 0.001000
iteration 20: error = 0.001000
iteration 30: error = 0.001000
iteration 40: error = 0.001000
iteration 50: error = 0.001000
iteration 60: error = 0.001000
iteration 70: error = 0.001000
iteration 80: error = 0.001000
iteration 90: error = 0.001000
iteration 100: error = 0.001000
iteration 200: error = 0.000999
iteration 300: error = 0.000999
iteration 400: error = 0.000999
iteration 500: error = 0.000998
iteration 600: error = 0.000998
iteration 700: error = 0.000998
iteration 800: error = 0.000997
iteration 

In [129]:
print NN.forward(inputs)

[[ 0.00921983]
 [ 0.99377714]
 [ 0.97837574]
 [ 0.00488943]
 [ 0.97837574]
 [ 0.0048895 ]
 [ 0.02949926]
 [ 0.99520102]]
